<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageId>ConcurrentJobEngine.Core</PackageId>
    <Version>1.0.0</Version>
    <Authors>Ali Gohar</Authors>
    <Company>Ali Gohar</Company>
    <Description>Core abstractions, interfaces, and domain models for ConcurrentJobEngine.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>job-processor queue priority-queue worker-pool concurrency async retry-policy dotnet csharp</PackageTags>
    <RepositoryUrl>https://github.com/AliGohar2151/ConcurrentJobEngine.git</RepositoryUrl>
  </PropertyGroup>

</Project>
